sudo: required

language: cpp       

services:
    - docker

before_install:
    - docker build -t alkevich/hello-cpp .

deploy:
    provider: script
    script: sh .travis/deploy_dockerhub.sh
    on:
        branch: master
