dist:     bionic
sudo:     required

language: cpp       

os:
    - linux

compiler:
    - gcc

env:
    - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug

install:
    - source install.sh

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
