#pragma once

#include "Entity.hpp"
#include "EntityManager.hpp"
#include "System.hpp"
#include "SystemStack.hpp"

#include "AIComponent.hpp"
#include "AnimationComponent.hpp"
#include "CameraComponent.hpp"
#include "CollisionComponent.hpp"
#include "FrameAnimationComponent.hpp"
#include "GroundComponent.hpp"
#include "InteractionComponent.hpp"
#include "LocationComponent.hpp"
#include "MaterialComponent.hpp"
#include "MorphingComponent.hpp"
#include "ObstacleComponent.hpp"
#include "ParalaxScrollingComponent.hpp"
#include "ParentComponent.hpp"
#include "PointLightComponent.hpp"
#include "RenderComponent.hpp"
#include "RigitBodyComponent.hpp"
#include "SpotLightComponent.hpp"
#include "SteeringComponent.hpp"
#include "TextureComponent.hpp"
#include "VelocityComponent.hpp"